export const EVENT_TYPE = {
    wallet_fund: 'wallet_fund',
    data_topup: 'data_topup',
    airtime_topup: 'airtime_topup',
    tv_topup: 'tv_topup',
    meter_topup: 'meter_topup',
    education_topup: 'education_topup',
    debit_funds: 'debit_funds',
    wallet_fund_failed: 'wallet_fund_failed',
    cashback: 'cashback',
    reverse_transaction: 'reverse_transaction',
    transfer_sent: 'transfer_sent',
    transfer_received: 'transfer_received',
    money_transfer: 'money_transfer',
} as const